### ISSUE TITLE
Delete Realm function from ROS Dashboard

### ISSUE THREAD

**Issue by ianbradbury-bizzibody** [realm/realm-mobile-platform#122] opened 2017-02-01 08:12 UTC
## Goals

The goal being to allow ROS administrators to delete Realm's form using the Dashboard interface.

## Expected Results

When viewing the list of Realms using the ROS dashboard ( `/#!/realms` ) I would expect to see a DELETE button/icon to the right of each Realm.  Clicking the DELETE button would prompt the user to confirm deletion, either by simply clicking yes, or having to retype the name of the Ream (like GitHub delete repo).

**Comment by teotwaki** [comment] 2017-02-03 15:43
Duplicate of #13.

**Closed by teotwaki** 2017-02-03 15:43 UTC
Labels: S:P2 Backlog, T:Feature
