### ISSUE TITLE
Unable to sync data between fully-privileged admin users with read-only non-admin users

### ISSUE THREAD

**Issue by damianogiusti** [realm/realm-mobile-platform#185] opened 2017-05-12 07:28 UTC
## Goals

I want to share and sync a Realm created from an admin user (which can read, write and manage it) with some non-admin users (with read-only permissions)

## Expected Results

When admin user writes some new data into the shared Realm, non-admin users should receive the updates from the server.
When the non-admin users try to write into the shared Realm having read-only permission, the write operation should fail.

## Actual Results

When admin user writes some new data into the shared Realm, the non-admin users do not receive the updates from the server. Only when the Realm is closed and re-opened with the same configuration, the updates are synced.
When the non-admin users try to write into the shared Realm having read-only permission, the write operation completes successfully without any error message, but the changes are not synced (and that last one I think it's right).

## Steps to Reproduce

- With the admin user, create a new Realm (let's say `/shared`) by connecting to the server with a `SyncConfiguration` (example realm url: `realm://192.168.20.100:9080/shared`)
- Create a new user from the admin panel
- With the admin user, make a `PermissionChange` targetting the newly created user, granting him read-only permissions on `/shared` 
- Insert new values on `/shared` using the admin user and the new user
- Described behaviour happens

**Comment by mrackwitz** [comment] 2017-05-15 10:57
Thanks for taking the time and filling out the issue template. First of all , let me clarify that support for opening read-only Realms isn't quite fully there yet across all our client SDKs. I wouldn't expect though any of the behavior you described here.

>When admin user writes some new data into the shared Realm, the non-admin users do not receive the updates from the server. Only when the Realm is closed and re-opened with the same configuration, the updates are synced.

All non-admin users should receive updates from the server, without having to re-open the Realm in between. 
What client SDKs do you use in which versions?
How do you open the Realm from the admin user?

>When the non-admin users try to write into the shared Realm having read-only permission, the write operation completes successfully without any error message, but the changes are not synced (and that last one I think it's right).

The expected behavior here would be that the write operation would fail. With the cocoa SDKs of Realm, you would need to open the Realm via `openAsync` and avoid any write transaction for now as it would fail the connection irrecoverably. How do you open the Realm from the non-admin user?

**Comment by damianogiusti** [comment] 2017-05-15 19:23
> What client SDKs do you use in which versions?

Sorry, I'm using the Android SDK, in particular `realm-gradle-plugin` version `3.1.4`

> How do you open the Realm from the admin user?

First I created the Realm with the `SyncConfiguration` pointing to let's say `realm://192.168.20.100:9080/shared`, then when I wanted to use that Realm, I simply recreated the `SyncConfiguration` with that url.

```java
String realmUrl = String.format("realm://192.168.20.100:9080/shared", OBJECT_SERVER_IP, BASE_PORT);
SyncConfiguration syncConfiguration = new SyncConfiguration.Builder(SyncUser.currentUser(), realmUrl).build();
Realm realm = Realm.getInstance(syncConfiguration);
```


> How do you open the Realm from the non-admin user?

For the non-admin user, I use the same `SyncConfiguration` with the `realm://192.168.20.100:9080/shared` url.
It seems that the new inserted values are kept only in the local Realm named `shared`, and as I said they're not synced, and I think that's right, because the non-admin user has read-only permissions.
For inserting new values, I used the following:

``` java
realm.executeTransaction(realm -> {
     realm.insertOrUpdate(myNewObject);
});
```

**Comment by mrackwitz** [comment] 2017-05-31 18:04
Can you confirm via the dashboard that the `PermissionChange` actually takes place? This could be very likely also affected by a bug we just discovered and solved where admin users can't apply permission changes to unowned Realm files as e.g. in the global scope. A bug fix release will be on the way soon.

**Comment by dalinaum** [comment] 2017-06-02 09:20
Can you share your project or make a small project to reproduce your problem?  If you can share a project to help@realm.io, it will really helpful to us. Of course, I will make a small project to test this problem.

**Comment by bmunkholm** [comment] 2017-07-04 08:13
Hi @damianogiusti. I'm closing this due to lacking response, assuming your have gotten around the problem. If that's not the case feel free to reopen.

**Closed by bmunkholm** 2017-07-04 08:13 UTC
Labels: S:Waiting For User, T:Help
