### ISSUE TITLE
Realm readable/writable for every user apparently not working

### ISSUE THREAD

**Issue by tsebastiani** [realm/realm-mobile-platform#141] opened 2017-02-28 13:50 UTC
## Goals

I want to have a sync realm accessible by all the users in read-write mode

## Expected Results

The sync realm "/common" supposed to have read-write access to all users

## Actual Results

the command seems to have success (no error or warning is shown, on the server logs there are no errors or warnings),  but the realm "/common" is read-only access (from the web panel) and all the user connections are dropped because the access Is denied.

## Code Sample
```
            let managementRealm = try! SyncUser.all["admin"]?.managementRealm()
            try! managementRealm?.write {
                let permissionChange = SyncPermissionChange(realmURL:"realm://192.168.250.96:9080/common",    // The remote Realm URL on which to apply the changes
                    userID: "*", // The user ID for which these permission changes should be applied
                    mayRead: true,         // Grant read access
                    mayWrite: true,        // Grant write access
                    mayManage: false)      // Grant management access
                managementRealm?.add(permissionChange)
```
## Version of Realm and Tooling

Realm Object Server Version: 1.1.0 Ubuntu
Flavor: Developer

Server OS & Version: Ubuntu 16.04 LTS

Client SDK Version: 2.3.2

Client OS & Version: 2.3.2

**Comment by istx25** [comment] 2017-02-28 18:58
Hi @tsebastiani. Thanks for reaching out about this. Someone will review what you've provided with us and follow-up with you soon. Cheers!

**Comment by bigfish24** [comment] 2017-03-02 00:16
@tsebastiani couple points:

1. By default Realm users can only create Realms in their scoped directory, i.e. `/~/myRealm` (where the `~` is simply short-hand for that user's Realm ID). The only exception to this rule is admin users. Today, the only way to create an admin user is through the dashboard. These users can create Realms in any directory.
  
    Thus to create `/common` would require an admin user to create it.

2. The ability to change permissions on a Realm is signified by the `manage` permission. By default only the user that created the Realm has manage permissions on it to start. Thus, based on my first point, this means that the admin user that created `/common` must then also be the user that creates the `SyncPermissionChange` to grant read/write access to all users.

3. Is: `let managementRealm = try! SyncUser.all["admin"]?.managementRealm()` appears incorrect. The API `SyncUser.all()` is not an API to retrieve any user of the application, but rather just a way to work with multiple `SyncUser` objects persisted on the client. This is only relevant if you app support multiple users. We are working on a client API to search or lookup a `SyncUser` from the global list (which has been [requested by others](https://github.com/realm/realm-mobile-platform/issues/142))

**Comment by mklb** [comment] 2017-03-17 14:18
I have the same problem with using javascript. The realm is created, but not with an mayWrite access. It's read only as the web interface / realm browser indicates. Also, toggling the mayWrite via the realm browser does not help. I can't write to the realm when the user is not an admin..

```
if (Realm.Sync.User.current.isAdmin) {
  // create realm
  this.globalRealm = new Realm({
    schema: [..],
    sync: {
      Realm.Sync.User.current,
      url: "realm://localhost:9080/global",
    },
  })
  // update permissions for all users
  var managementRealm = Realm.Sync.User.current.openManagementRealm()
  managementRealm.write(() => {
    managementRealm.create('PermissionChange', {
      id: "xxxx",
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: "*",
      realmUrl: "realm://localhost:9080/global",
      mayRead: true,
      mayWrite: true
    })
  })
}
```

**Comment by austinzheng** [comment] 2017-03-29 15:11
Thanks for getting in touch with us @mklb, and sorry for the delayed response. Nothing in your sample code stands out to me as being incorrect. Would you be willing to send us a reproduction project to help@realm.io so we can investigate this issue further?

**Comment by teotwaki** [comment] 2017-04-18 09:07
@austinzheng Can you post a status update on this?

**Comment by austinzheng** [comment] 2017-04-18 16:38
Without a reproduction project we can't really do anything. Sorry.

**Comment by teotwaki** [comment] 2017-04-21 11:21
@mklb Can you help us out? Thanks.

**Comment by radu-tutueanu** [comment] 2017-05-15 11:32
Closing the issue since no reproduction  info was provided.

**Closed by radu-tutueanu** 2017-05-15 11:32 UTC
Labels: Reproduction Required, S:Waiting For User, T:Help

**Comment by mklb** [comment] 2017-06-07 09:32
Sorry for not responding. I just created a shared realm via the Realm Browser as a work around: 

I created an entry in the _admin realm with a nil user pointing to the realm I want to give default read/write permissions to with mayRead and mayWrite checked. It worked perfectly but I just updated to the "latest" version of the realm platform 1.7.4 where this does not work anymore. See: https://github.com/realm/realm-mobile-platform/issues/199  It should work again in 1.7.5 as far as I can understand

**Comment by mklb** [comment] 2017-11-14 11:40
__UPDATE__

The "architecture" has changed since Realm Object Server 2.0.. There is no `_admin`realm. I tried to create a wildcard entry in the new `/_wildcardpermissions` realm which somehow does not work as expected. So far I can not get a shared realm to work. It would be lovely to see a small tutorial on how to share a realm across all users @radu-tutueanu

**Comment by nirinchev** [comment] 2017-11-14 11:50
You can use the js SDK to modify permissions: https://realm.io/docs/javascript/latest/#granting-permissions

For `userId`, pass `*` to make it globally readable/writeable.

**Comment by mklb** [comment] 2017-11-23 11:36
I did the entry via the Realm Browser

**Comment by lemonkey** [comment] 2018-02-05 22:59
I too am stumped. The current documentation is misleading regarding "global" realms.

**Comment by lemonkey** [comment] 2018-02-05 23:00
Could this be due to the upcoming Realm Cloud product nerfing shared or global Realms?

**Comment by lemonkey** [comment] 2018-02-06 03:10
Was finally able to get this to work, but it doesn't seem that read-only is the default when no explicit permission exists for a global realm owned by an admin (even __admin).
