### ISSUE TITLE
Binding should refresh access token upon app reactivation

### ISSUE THREAD

**Issue by einsteinx2** [realm/realm-mobile-platform#152] opened 2017-03-17 03:25 UTC
## Goals

Continuous Realm syncing of a long running macOS app

## Expected Results

I expect that once authenticated, it will continue to sync

## Actual Results

After putting the computer to sleep, the app is unable to sync due to the following error:

Sync: Connection[2]: Connection closed due to error reported by server: Access token expired (202)

I have an error handler setup, but it's not firing for this error, so I'm not sure how to catch it and searching the documentation and GitHub issues hasn't yielded me any information on token expiration handling.

Relaunching the app seems to fix the issue.

## Steps to Reproduce

1. Lauch macOS app
2. Connect to synced Realm
3. Put machine to sleep for a while
4. Open machine

## Code Sample

Not sure what relevant code to put here, but here's how I'm setting my error handler (before opening any Realms)

```
RealmSwift.SyncManager.shared.errorHandler = { error, _ in
    print("Realm error: \(error)")
}
```

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32

/Applications/Xcode.app/Contents/Developer
Xcode 8.2.1
Build version 8C1002

/usr/local/bin/pod
1.2.0
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/local/bin/carthage
0.18.1
github "realm/realm-cocoa" "v2.4.4"

/usr/bin/git
git version 2.10.1 (Apple Git-78)
```

**Comment by istx25** [comment] 2017-03-17 19:41
Hi @einsteinx2. Thanks for reaching out. I'll escalate this to one of the Cocoa engineers. I don't have enough experience with RMP to know if this is a bug or from a problem with your code. Someone will follow-up with you soon with more questions and/or a solution. Cheers!

**Comment by jpsim** [comment] 2017-03-22 17:56
@einsteinx2 in the "version of Realm and tooling" section of your comment, you forgot to include the versions of Realm you're using. Could you please share which versions of Realm Swift and the Realm Object Server you're running? If you're not running Realm Swift 2.4.4 along with Realm Object Server 1.2.1, could you please update to those versions (latest as of this writing) and report back if you're still experiencing issues? Thanks!

**Comment by einsteinx2** [comment] 2017-03-22 18:40
I'm using the latest ROS version from about a week ago, but I'll double check the exact version when I get home.

**Comment by einsteinx2** [comment] 2017-03-22 22:57
@jpsim Yep it's 1.2.1

**Comment by einsteinx2** [comment] 2017-03-25 00:08
Any ideas on this? It's the only thing holding us back from deploying.

I _think_ I can work around it by just re-authenticating manually each time the computer wakes up, but I'm concerned about releasing with a workaround like that when I don't really understand the underlying problem.

**Comment by stel** [comment] 2017-03-28 08:32
@einsteinx2 sorry for delay in replying. @austinzheng could you please take a look on this, do you have any suggestions?

**Comment by jpsim** [comment] 2017-03-29 21:41
Austin's away for a few days, so he won't be able to investigate this. Could you share a sample project and steps to reproduce? That's the best way for us to look into issues like these.

**Comment by einsteinx2** [comment] 2017-03-30 21:05
I just upgraded to ROS 1.3.0 and the 2.5.0 cocoa framework. Will double check the problem still exists if so, then I'll try to get a simple test app put together.

**Comment by einsteinx2** [comment] 2017-04-03 19:21
So at first I had thought the problem was fixed, but now I had my laptop sleeping for the last day and a half, opened it up, and got the same problem. I've pasted the logs below. And again, my error handler is not being called even though the Realm framework is clearly logging an error.

I'll try and get a test app written today, but I think it's as simple as opening any remote realm db and letting your computer sleep for a while. Though maybe I'm doing something different that's triggering it.

```
2017-04-03 14:17:48.586475-0500 Balance[38723:3385713] Sync: Connection[1]: Resolving 'sync.balancemy.money:443'
2017-04-03 14:17:48.587619-0500 Balance[38723:3385713] Sync: Connection[1]: Connecting to endpoint '159.203.84.96:443' (1/1)
2017-04-03 14:17:48.711605-0500 Balance[38723:3385713] Sync: Connection[1]: Connected to endpoint '159.203.84.96:443' (from '192.168.2.117:60975')
2017-04-03 14:17:49.147694-0500 Balance[38723:3385713] Sync: Connection[1]: WebSocket::initiate_client_handshake()
2017-04-03 14:17:49.147774-0500 Balance[38723:3385713] Sync: Connection[1]: HTTP request =
GET /realm-object-server HTTP/1.1
Connection: Upgrade
Host: sync.balancemy.money
Sec-WebSocket-Key: KDtIArnIfC+fTE5d2PfKrQ==
Sec-WebSocket-Protocol: io.realm.protocol
Sec-WebSocket-Version: 13
Upgrade: websocket
X-Realm-Access-Token: eyJpZGVudGl0eSI6IjE0YWI5NDBmYzIzY2Q3YjYxZGFhMWY5MmY0N2QwOTAyIiwicGF0aCI6Ii8xNGFiOTQwZmMyM2NkN2I2MWRhYTFmOTJmNDdkMDkwMi9wcmVmcyIsImV4cGlyZXMiOjE0OTEwMTMwNjksImFwcF9pZCI6InNvZnR3YXJlLmJhbGFuY2VkLmJhbGFuY2VtYWMiLCJhY2Nlc3MiOlsiZG93bmxvYWQiLCJ1cGxvYWQiLCJtYW5hZ2UiXX0=:jZyoKAk00YkOQR7Z31DEZOQQcM8s4dLqBB3oorfyUsGfltUGlkodUcovZ3RoRUzD9QyUE+WNAd5NRs8yFyLYJJaFZIL7qlCXHSQyG4macmAphESci4sylkTK6F5pNBoGKAZAOz6WQVZsSaGdwllEyyREsSbMUnEPTeD9MN0arVbY/0qBNSLwVDwVybxjrx8JpjmFJGqp1i67XGsuAOIgVlMFXrFfZbrMLV8WGLP0pzOsbQF8lnP6fgLfHqVvohQlNv8cx2HPJ4LCD5U8RngiOemg+ys5RgjMJfTV8l7btGipvq5FhDXOzOicsrLZpG3QriL/nSLxbJqIkrhIXZlZzA==
X-Realm-Path: /14ab940fc23cd7b61daa1f92f47d0902/prefs
X-Realm-Protocol-Version: 17
2017-04-03 14:17:49.279503-0500 Balance[38723:3385713] Sync: Connection[1]: WebSocket::handle_http_response_received()
2017-04-03 14:17:49.279558-0500 Balance[38723:3385713] Sync: Connection[1]: Will emit a ping in 600000 milliseconds
2017-04-03 14:17:49.279578-0500 Balance[38723:3385713] Sync: Connection[1]: Session[1]: Sending: BIND(server_path='/14ab940fc23cd7b61daa1f92f47d0902/prefs', signed_user_token_size=609, need_file_ident_pair=0)
2017-04-03 14:17:49.279624-0500 Balance[38723:3385713] Sync: Connection[1]: handle_write_output_buffer
2017-04-03 14:17:49.279668-0500 Balance[38723:3385713] Sync: Connection[1]: Session[1]: Sending: IDENT(server_file_ident=9089591982362292851, client_file_ident=4, client_file_ident_secret=5033507404813758394, scan_server_version=117, scan_client_version=423, latest_server_version=117, latest_server_session_ident=8801463860093167006)
2017-04-03 14:17:49.279714-0500 Balance[38723:3385713] Sync: Connection[1]: handle_write_output_buffer
2017-04-03 14:17:49.279734-0500 Balance[38723:3385713] Sync: Using already open Realm file: /Users/bbaron/Library/Containers/software.balanced.balancemac/Data/Library/Application Support/realm-object-server/14ab940fc23cd7b61daa1f92f47d0902/realms%3A%2F%2Fsync.balancemy.money%2F%7E%2Fprefs
2017-04-03 14:17:49.423997-0500 Balance[38723:3385713] Sync: message_type = error
2017-04-03 14:17:49.424050-0500 Balance[38723:3385713] Sync: Connection[1]: Received: ERROR(error_code=202, message_size=20, try_again=0, session_ident=1)
2017-04-03 14:17:49.424165-0500 Balance[38723:3385713] Sync: Connection[1]: Connection closed due to error reported by server: Access token expired (202)
2017-04-03 14:17:49.424190-0500 Balance[38723:3385713] Sync: Connection[1]: Reconnecting in 18650 milliseconds
```

**Comment by einsteinx2** [comment] 2017-04-03 19:28
Also here are the server side logs (note that the connection comes from 127.0.0.1 because I'm using Nginx as a reverse proxy).

<img width="914" alt="screen shot 2017-04-03 at 2 27 35 pm" src="https://cloud.githubusercontent.com/assets/350423/24627251/c2d2e410-1879-11e7-94da-43e6de55b209.png">

**Comment by bigfish24** [comment] 2017-04-03 19:42
@kvap do you have any thoughts on this?

**Comment by kvap** [comment] 2017-04-04 12:33
@bigfish24 looks like `realm-object-store` does not call any error handlers in case of `token expired`:
https://github.com/realm/realm-object-store/blob/master/src/sync/sync_session.cpp#L440
```cpp
case ProtocolError::token_expired: {
    std::unique_lock<std::mutex> lock(m_state_mutex);
    // This isn't an error from the binding's point of view. If we're connected we'll
    // simply ask the binding to log in again.
    m_state->access_token_expired(lock, *this);
    return;
}
```

We can put `break` instead of `return` there, and then the handler will get called. But I don't know if it was intended by the author. @austinzheng, is the binding supposed to detect this condition and call `refresh_access_token`?

**Comment by austinzheng** [comment] 2017-04-04 18:36
We explicitly don't call error handlers when the `token_expired` error is fired. The call to `access_token_expired()` handles asking the binding to refresh the access token. Note that if the binding is not in the `active` state when that error is fired, nothing will actually happen.

**Comment by einsteinx2** [comment] 2017-04-06 01:42
@austinzheng Can you elaborate on this "Note that if the binding is not in the active state when that error is fired, nothing will actually happen."?

Is there something I should be doing to ensure that it's in the active state? Should I just re-authenticate every time the computer wakes? Or is this still some kind of bug in Realm? Is there any documentation about this?

I assume (potentially incorrectly), that I can just open an ROS synced DB, and it should work for the life of the application launch. Is this an incorrect assumption?

Our app is a menu bar app that (generally) launches on computer startup and runs continuously until the computer is shut down, potentially for weeks or months, and potentially through multiple computer sleep states. If there's something simple I need to do to keep the connection alive, that's fine. But right now it seems I can't detect this situation because the error handler isn't being called, so all I can do is blindly re-authenticate, which maybe is fine? Though it seems to me that if something is being logged as an error, that the error handler should be called, no?

**Comment by austinzheng** [comment] 2017-04-06 17:32
To be clear, the 202 error is _not_ something the user is expected to see or handle manually. The binding is expected to handle refreshing the token automatically.

It seems that to fix this bug the sync binding should register for a notification when the app becomes active, and pre-emptively refresh the token then. Until then you can manually refresh the token whenever your app resumes to work around this issue.

**Comment by einsteinx2** [comment] 2017-04-06 19:16
@austinzheng Just to confirm, when you say refresh the token, do you mean I should call SyncUser.logIn() again or something else?

**Comment by einsteinx2** [comment] 2017-04-13 16:55
So I tried calling login() again when the app wakes up, that seems to reconnect the db but I still get the log messages about token retrying constantly. Can @austinzheng, @kvap, or someone please confirm that that is the recommended workaround? Is there anything I can do to get it to stop retrying to the token and failing over and over? Should I be calling something other than login(), or doing something else first/after? 

I'm concerned about potential issues as a user's machine goes to sleep and wakes many times during app lifetime and there being some uncontrolled background thread constantly retrying something that keeps failing that I have no control over.

This bug is the only thing holding us back from deploying for weeks now, a direct answer on exactly the recommended solution until this bug is fixed would be great, thanks.

**Comment by austinzheng** [comment] 2017-04-17 19:36
Very sorry for the slow response. Right now there isn't a straightforward way to manually force the refresh to take place.

We are looking into ways to properly solve this issue. In the meantime, you can probably use our private APIs to work around this issue:

```objc
// (Register a notification upon app wake and then use this as the callback)
- (void)onAppWake {
  for (RLMSyncUser *user in [RLMSyncUser allUsers]) {
    for (RLMSyncSessionRefreshHandle *handle in [user refreshHandles]) {
      [[handle timer] invalidate];
      [handle _timerFired:nil];
    }
  } 
}
```

You will need to forward declare all the methods that aren't part of the public API. You'll also need to make sure that the wake notification isn't fired before the computer re-establishes wi-fi or Ethernet connectivity, and deal with that appropriately otherwise. Please feel free to continue this thread if you have any questions. Hope that helps, and again my deepest apologies for the inconvenience.

**Comment by gritzko** [comment] 2017-06-06 14:11
What's the progress on this?

**Comment by einsteinx2** [comment] 2017-06-09 12:56
The workaround is not reliable. I've run into a random crash due to a handle apparently being deallocated on another thread. So far still can't ship our Realm support as I've had minimal extra time to dedicate to this problem. A fix in the SDK would be ideal.

**Comment by austinzheng** [comment] 2017-06-13 06:38
My deepest apologies for how long this issue has taken to resolve.

In our latest version of Realm Cocoa, we include [a SDK-level fix](https://github.com/realm/realm-cocoa/pull/4957) for this issue. To be completely sure, though, I will spend some time tomorrow reproducing your test scenario to ensure that this fix really does address your bug.

Again, sorry for all the inconvenience and thanks for using Realm.

**Comment by netspencer** [comment] 2017-06-14 20:41
I also have this issue:

```
2017-06-14 13:24:55.529357-0700 LilYachty[13194:4518698] Sync: Connection[1]: Session[1]: Sending: REFRESH(signed_user_token_size=681)
Message from debugger: Terminated due to memory issue

```

**Comment by austinzheng** [comment] 2017-06-14 22:10
That doesn't look like the same issue. Please file a new ticket with a stack trace, version of Realm, sample code, and reproduction steps.

**Comment by bmunkholm** [comment] 2017-07-04 08:28
@einsteinx2 Did the latest fix solve your problem?

**Comment by einsteinx2** [comment] 2017-07-04 10:05
I added it and removed the workaround. A quick test seems to indicate it worked, but we'll be testing properly this week so I'll report back in a day or two.

**Comment by mklb** [comment] 2017-07-04 10:50
I dont really know if this is related. I get a (different) session refresh error after running an app for a view minutes in react native on iOS:
```
Unhandled session token refresh error: could not look up session at path /Users/XXXXXXX/Library/Developer/CoreSimulator/Devices/85A472DA-CBCB-416B-871B-50CA0DC03DFD/data/Containers/Data/Application/865345A1-6C84-4470-8055-0F9A65A86452/Documents/realm-object-server/dfeddc7733c15fb2b3108c217c1ce0db/realm%3A%2F%2Flocalhost%3A9080%2F%7E%2F__management
```

React native: 0.45.1
React: 15.6.1
Realm: 1.8.3
Realm Obj. Server: 1.7.6
Simulator Device Version: iOS 10.3

**Comment by einsteinx2** [comment] 2017-07-04 10:59
@mklb that doesn't appear to be related, this was a timer failing to be reset on app wake. You should post that as a new issue.

**Comment by bmunkholm** [comment] 2017-07-04 15:20
@einsteinx2 Thanks - I'll close this one then for now. Feel free to reopen in case it's not fully solved then.

**Closed by bmunkholm** 2017-07-04 15:20 UTC
Labels: T:Bug
