### ISSUE TITLE
Realm persistent data issue between threads

### ISSUE THREAD

**Issue by donelasurya** [realm/realm-mobile-platform#239] opened 2017-07-13 09:25 UTC
I am new to Realm. We are facing a weird issue. We saved an entry using copytorealm in execute transaction and when we checked the db the entry in same thread (not main) was present. But later when we queried the same entry from MAIN Thread, strangely, we received null.

**Comment by bmunkholm** [comment] 2017-07-13 12:38
@donelasurya Please use the issue template and fill in all the information requested. In particular, please describe this problem with code sample so we can reproduce.
Also please consider to post the question on Stackoverflow unless you have a repro case that indicates a bug. Thanks!

**Comment by bmunkholm** [comment] 2017-08-20 08:58
Closing due to lacking response here. Please provide additional info and reopen the issue if needed.

**Closed by bmunkholm** 2017-08-20 08:58 UTC
Labels: S:Waiting For User, T:Help
