### ISSUE TITLE
Authentication Bug or Intended?

### ISSUE THREAD

**Issue by TotemChris** [realm/realm-mobile-platform#28] opened 2016-10-21 21:16 UTC
I have a single Realm file on the ROS server that I have multiple users pointing at.  When calling authenticate() for the first time with a user, my Realm() comes back empty after I set the default realm sync configuration.  This only happens on the first successful login for that user.  Every time thereafter, it works works just fine, and I get false for .isEmpty.  This happens with each successive "new" user on that device.  I have a feeling this is due to the fact that there isn't a local version of the realmfile yet until the scope of this call exits (maybe?).  If that is the case, is there a way to guarantee the realm is populated even on the first login within this completionHandler?  I tried using .refresh() and also tried forcing a Realm().commitWrite.  Neither helped.  Later one crashed.

To reproduce, drop this in an appDelegate didFinishLaunching method call, and populate with valid creds, authURL, and realmURL.

    SyncUser.authenticate(with: creds, server: authURL) { user, error in
            guard let user = user else {
                print(error!)
                return
            }
            
            Realm.Configuration.defaultConfiguration = Realm.Configuration(syncConfiguration: (user, realmURL))
            print("isEmpty: \(try! Realm().isEmpty)")
        }

**Comment by mrackwitz** [comment] 2016-10-25 08:57
This is largely indeed the intended behavior.

>I have a feeling this is due to the fact that there isn't a local version of the realmfile yet until the scope of this call exits (maybe?).

Not exactly. It isn't bound to the scope of this call specifically. A synchronized Realm you open is not synchronously downloaded. Instead it will open up a connection in the background to the server to download existing history. But it will be instantly available for writes, even if you go offline.

> I tried using .refresh() and also tried forcing a Realm().commitWrite. Neither helped. Later one crashed.

What was the crash you were seeing for `realm.commitWrite()`? If this was an unmatched call without beginning a write transaction first, then this would be expected.

> If that is the case, is there a way to guarantee the realm is populated even on the first login within this completionHandler?

There is no way to guarantee that the Realm will be populated within the completion handler as it would be also bad practice to expose such an expensive asynchronous operation in a synchronous way. You will be notified though about remote changes just in the same way as about local changes and can [rely on the same notification mechanisms](https://realm.io/docs/swift/latest/#notifications). So you can instead query for specific objects you would expect or want to display once the Realm is readily populated. On these returned `Results` you can then setup a listener to be called whenever there are new objects. You can also do this for the whole file or individual object properties via KVO.

Beyond that we're working on a dedicated API which allows to download an existing API asynchronously and getting a callback once that succeed or failed due to an error.

**Comment by TotemChris** [comment] 2016-10-25 11:34
Ok this clarifies it for me.  I was looking at this with some tunnel vision and was too eager to get at the data before it existed :)  I will rework around notifications.  Thanks!

**Closed** 2016-10-25 11:36 UTC
Labels: T:Help
