### ISSUE TITLE
Error opening realm of 100000 objects

### ISSUE THREAD

**Issue by FreudGit** [realm/realm-mobile-platform#187] opened 2017-05-17 23:37 UTC
Hi.

A create a realm Db of 100000 objects.

When I delete the app, and try to sync(get object), I get error.

> BIND(server_path='/beerUsers20170517d80', signed_user_token_size=573, need_file_ident_pair=0)
> 2017-05-17 19:32:06.662 1001 Bieres_sw[57115:7062864] Sync: Connection[1]: Session[1]: Sending: IDENT(server_file_ident=1, client_file_ident=11, client_file_ident_secret=2790726433088945550, scan_server_version=0, scan_client_version=0, latest_server_version=0, latest_server_session_ident=0)
> 2017-05-17 19:32:09.334 1001 Bieres_sw[57115:7062864] Sync: Connection[1]: Reading failed: End of input
> 2017-05-17 19:32:09.334 1001 Bieres_sw[57115:7062864] Sync: Connection[1]: Connection closed due to error
> 2017-05-17 19:32:09.335 1001 Bieres_sw[57115:7062864] Sync: Connection[1]: Resolving 'ec2-54-84-221-150.compute-1.amazonaws.com:9080'
> 2017-05-17 19:32:09.336 1001 Bieres_sw[57115:7062864] Sync: Connection[1]: Connecting to endpoint '54.84.221.150:9080' (1/1)
> 2017-05-17 19:32:09.364 1001 Bieres_sw[57115:7062864] Sync: Connection[1]: Failed to connect to endpoint '54.84.221.150:9080': Connection refused
> 2017-05-17 19:32:09.365 1001 Bieres_sw[57115:7062864] Sync: Connection[1]: Failed to connect to 'ec2-54-84-221-150.compute-1.amazonaws.com:9080': All endpoints failed

Please note that from Realm browser, I also get: "Realm couldn't be opened"

When I try using a realm with 50000 objects, everything's ok.

realm-object-server-developer (1.5.0-318)
Realmswift up to date (using pod)

**Comment by radu-tutueanu** [comment] 2017-05-18 13:28
Thank you for logging the issue, @FreudGit. Could you please provide the app code or describe what the objects contain?
I will try to reproduce the issue.

**Comment by FreudGit** [comment] 2017-05-18 16:08
Contact me @ francois.hebert@gmail.com, i'll provide details.

**Comment by bmunkholm** [comment] 2017-05-19 06:59
@FreudGit Can you send us the details at help@realm.io and reference this issue?
Thanks!

**Comment by FreudGit** [comment] 2017-05-19 12:18
Sent.

**Comment by FreudGit** [comment] 2017-05-20 13:10
Any status?

**Comment by jpsim** [comment] 2017-05-30 23:16
Yes, I replied to your email.

**Comment by avitus** [comment] 2017-05-31 23:24
I am also seeing this (potentially related) error fairly frequently.

```
2017-05-31 16:19:28.703 Memlogos[5159:195965] Sync: Connection[2]: Reading failed: End of input
2017-05-31 16:19:28.703 Memlogos[5159:195965] Sync: Connection[2]: Connection closed due to error
2017-05-31 16:19:28.704 Memlogos[5159:195965] Sync: Connection[2]: Resolving 'realm.andyvitus.com:80'
2017-05-31 16:19:28.705 Memlogos[5159:195965] Sync: Connection[2]: Connecting to endpoint '192.241.205.154:80' (1/1)
2017-05-31 16:19:28.731 Memlogos[5159:195965] Sync: Connection[2]: Connected to endpoint '192.241.205.154:80' (from '172.19.248.230:55220')
2017-05-31 16:19:29.922 Memlogos[5159:195965] Sync: Connection[2]: HTTP: Failed to switch protocols (response status = 502)
2017-05-31 16:19:29.922 Memlogos[5159:195965] Sync: Connection[2]: Connection closed due to error
```

I have about 40K objects in my Realm. I also seem to stop getting notifications on changes to the collection but I'm still investigating that.

**Comment by bmunkholm** [comment] 2017-06-02 15:20
@avitus Could you please post that as a separate issue? Preferably with some indications as to how to reproduce it. Thanks!

**Comment by morten-krogh** [comment] 2017-06-02 18:06
@avitus 
If you turn on debug logging and send the log files, I would be happy to look at it.

**Comment by bmunkholm** [comment] 2017-07-04 08:18
@FreudGit @avitus Can you confirm if your issues are resolved?

**Comment by bmunkholm** [comment] 2017-08-20 08:47
Closing this due to lacking response. Please open a new issue if a similar problem occurs.

**Closed by bmunkholm** 2017-08-20 08:47 UTC
Labels: S:Waiting For User, T:Bug
