### ISSUE TITLE
Create or use existing

### ISSUE THREAD

**Issue by codefriar** [realm/realm-mobile-platform#36] opened 2016-10-31 18:20 UTC
Is it possible to authenticate using .usernamePassword in such a way that if the user account does exist, it uses it, and if it does not, it creates it? 

I'm looking at a situation where I want the app to automatically register if need be.

**Comment by cliftonlabrum** [comment] 2016-10-31 19:16
As far as I know, you can already do this (with a couple limitations). Below is a possible workflow in Swift:
```
//Sign in
SyncUser.authenticate(with: Credential.usernamePassword(username: user.text!, password: password.text!, actions: [.useExistingAccount]), server: URL(string: address)!, onCompletion: { user, error in
  if user == nil {
    //Sign in error; create a new account account instead
    SyncUser.authenticate(with: Credential.usernamePassword(username: user.text!, password: password.text!, actions: [.createAccount]), server: URL(string: address)!, onCompletion: { user, error in
    //...
    })
  }
})
```

There are a couple significant issues with this:
1. As far as I know, there is now way to tell whether the authentication error is caused by an incorrect password or there not being a matching username in the system.
2. The user could make a username typo and inadvertently create a new account instead of pulling down their existing account.

Once the errors returned by the `authenticate` call are more meaningful, this feature becomes much more feasible.

**Comment by jpsim** [comment] 2016-11-01 11:04
`AuthenticationActions` is an option set, which means you can do "create or use existing" by passing in `[.useExistingAccount | .createAccount]`

**Comment by codefriar** [comment] 2016-11-01 14:02
That actually produces an error: No ‘|’ candidates produce contextual result type RLMAuthenticationActions.

**Comment by jpsim** [comment] 2016-11-01 15:01
Oops, syntactical mistake when writing my last comment, should be a comma instead of `|`: `[.useExistingAccount, .createAccount]`

**Comment by codefriar** [comment] 2016-11-01 15:06
That was my original stab at this. Unfortunately, both options will return an error, and it appears that the code will actually only function on  the first in the list.

 

Thus, if you say .useExistingAccount, .createAccount it will fail when you need to create an account, and inversely, if you say .createAccount, .useExistingAccount, it will fail if the account already exists.

 

I’ve implemented the first suggestion of a if user == nil block, which works, but isn’t very dry.

 

-pkj

**Comment by jpsim** [comment] 2016-11-07 19:40
> Unfortunately, both options will return an error, and it appears that the code will actually only function on  the first in the list.

You're right. There are some issues with the current API. That's mostly a historical accident of exploring different directions for this API that weren't fully reconsidered after shipping our initial version a few weeks ago.

It doesn't actually make sense to have a "create OR use existing" mode for the username/password credential because a user interface should always expose an explicit action. Example: you wouldn't want someone logging in with a typo in their email to accidentally create an account!

This is only an issue with the cocoa SDKs, as Java already exposes this correct (a boolean flag for `register` on the username/password credential constructor). So I've created realm/realm-cocoa#4303 to track on the cocoa issue tracker and will be closing this ticket.

@codefriar let's move the conversation to realm/realm-cocoa#4303.

**Closed by jpsim** 2016-11-07 19:40 UTC
Labels: S:Waiting For User, T:Help
