### ISSUE TITLE
Error: Failed to resolve ':::9080'

### ISSUE THREAD

**Issue by Igralino** [realm/realm-mobile-platform#175] opened 2017-04-18 12:38 UTC
## Goals

Just perfectly working Realm Object Server
Possibility to connect there via Realm Browser

## Expected Results

No errors in log file
Connection to see realms via Realm Browser

## Actual Results
Realm browser is not connecting to server.
A lot of errors in Log file:

```
2017-04-17T20:05:27.767Z - info: Backup admin-Realm file written to /var/lib/realm/object-server/internal_data/oldAuth.realm.bak (in case of unexpected failures during the upgrade).
2017-04-17T20:05:28.020Z - info: Realm Object Server sync engine listening on 127.0.0.1:27800.
2017-04-17T20:05:28.133Z - info: permission: Seed permission-Realms
2017-04-17T20:05:28.262Z - info: Realm Object Server web server listening on 127.0.0.1:27080.
2017-04-17T20:05:28.274Z - info: http proxy listening on :::9080.
2017-04-17T20:05:28.275Z - info: The Realm Object Server requires an initial admin user to start. To continue, please open your web browser to access the dashboard at: http://127.0.0.1:27080 and register your user.
2017-04-17T20:05:28.279Z - info: sync-server: Realm sync server started ([realm-core-2.5.1], [realm-sync-1.5.0])
2017-04-17T20:05:28.279Z - info: sync-server: Directory holding persistent state: /var/lib/realm/object-server/0/user_data
2017-04-17T20:05:28.279Z - info: sync-server: Listening on 127.0.0.1:27800 (sync protocol version 17)
2017-04-17T20:05:28.279Z - info: client: Opening Realm file: /var/lib/realm/object-server/internal_data/auth.realm
2017-04-17T20:05:28.279Z - info: client: Connection[1]: Session[1]: Starting session for '/var/lib/realm/object-server/internal_data/auth.realm'
2017-04-17T20:05:28.279Z - info: client: Connection[1]: Resolving ':::9080'
2017-04-17T20:05:28.279Z - error: client: Connection[1]: Failed to resolve ':::9080': Host not found (authoritative)
2017-04-17T20:05:28.279Z - info: client: Opening Realm file: /var/lib/realm/object-server/tmp/realm-object-server/listener/__admin.realm
2017-04-17T20:05:28.279Z - info: client: Connection[2]: Session[1]: Starting session for '/var/lib/realm/object-server/tmp/realm-object-server/listener/__admin.realm'
2017-04-17T20:05:28.279Z - info: client: Connection[2]: Resolving ':::9080'
2017-04-17T20:05:28.280Z - error: client: Connection[2]: Failed to resolve ':::9080': Host not found (authoritative)
2017-04-17T20:05:28.280Z - info: client: Opening Realm file: /var/lib/realm/object-server/internal_data/permission/__auth.realm
2017-04-17T20:05:28.280Z - info: client: Connection[3]: Session[1]: Starting session for '/var/lib/realm/object-server/internal_data/permission/__auth.realm'
2017-04-17T20:05:28.280Z - info: client: Connection[3]: Resolving ':::9080'
2017-04-17T20:05:28.280Z - error: client: Connection[3]: Failed to resolve ':::9080': Host not found (authoritative)
2017-04-17T20:05:28.280Z - info: client: Opening Realm file: /var/lib/realm/object-server/internal_data/permission/__global.realm
2017-04-17T20:05:28.281Z - info: client: Connection[4]: Session[1]: Starting session for '/var/lib/realm/object-server/internal_data/permission/__global.realm'
2017-04-17T20:05:28.281Z - info: client: Connection[4]: Resolving ':::9080'.
```
After that it is going to write the same errors. Round and round

```
2017-04-17T20:05:28.281Z - error: client: Connection[4]: Failed to resolve ':::9080': Host not found (authoritative)
2017-04-17T20:05:28.956Z - info: client: Connection[2]: Resolving ':::9080'
2017-04-17T20:05:28.957Z - error: client: Connection[2]: Failed to resolve ':::9080': Host not found (authoritative)
2017-04-17T20:05:28.993Z - info: client: Connection[3]: Resolving ':::9080'
2017-04-17T20:05:28.993Z - error: client: Connection[3]: Failed to resolve ':::9080': Host not found (authoritative)
2017-04-17T20:05:29.016Z - info: client: Connection[1]: Resolving ':::9080'
2017-04-17T20:05:29.016Z - error: client: Connection[1]: Failed to resolve ':::9080': Host not found (authoritative)
2017-04-17T20:05:29.093Z - info: client: Connection[4]: Resolving ':::9080'
2017-04-17T20:05:29.094Z - error: client: Connection[4]: Failed to resolve ':::9080': Host not found (authoritative)
```
<img width="761" alt="2017-04-18 15 42 05" src="https://cloud.githubusercontent.com/assets/11150993/25131247/aa3ff7dc-244d-11e7-8348-92b7e701f523.png">

## Steps to Reproduce

Rent new VPS server with Ubuntu 16.04

1. Rent new VPS server with Ubuntu 16.04
2. Do this steps:
```
curl -s https://packagecloud.io/install/repositories/realm/realm/script.deb.sh | sudo bash
sudo apt-get update
sudo apt-get install realm-object-server-developer
sudo systemctl enable realm-object-server
sudo systemctl start realm-object-server
```
3. Go to your_server_ip/#!/logs
4. See a lot of error in the logs.

## Version of Realm and Tooling

Realm Object Server version: 1.4.1 (the last one)
Realm Browser version: 2.1.7

**Comment by teotwaki** [comment] 2017-04-18 13:09
Hi @Igralino,

Thanks for the report. We'll have somebody looking into this ASAP. Could you post the error from the logs?

**Comment by Igralino** [comment] 2017-04-18 13:18
@teotwaki 
That's the Log file from my server:

[realm-object-server.log.zip](https://github.com/realm/realm-mobile-platform/files/929756/realm-object-server.log.zip)

**Comment by alebsack** [comment] 2017-04-18 13:59
Hi @Igralino,

I've tried to reproduce this myself and initially I could not -- but then I disabled IPv6 on my system.  Then I got the same error logs that you did.

I would suggest modifying your configuration file as follows:

```
proxy:
  http:
    listen_address: '0.0.0.0'
```

The value above is `::` by default, which is equivalent to `0.0.0.0` when using IPv6.

**Comment by Igralino** [comment] 2017-04-18 14:07
@alebsack 
I changed it:
<img width="990" alt="2017-04-18 17 05 57" src="https://cloud.githubusercontent.com/assets/11150993/25134853/5dd9ddf2-2459-11e7-95df-73db162f122c.png">
And nothing changed in the log:
![2017-04-18 17 06 52](https://cloud.githubusercontent.com/assets/11150993/25134885/70ae13d0-2459-11e7-95f0-2eb79df2f7e7.png)

**Comment by Igralino** [comment] 2017-04-18 14:13
@alebsack OK. I've restarted the server. Now there is such information in the log:
![2017-04-18 17 10 11](https://cloud.githubusercontent.com/assets/11150993/25135093/0be50f2a-245a-11e7-9bd9-b6e63c220eaa.png)
I think that it is OK. And I can close issue. Am I right?
(Or it have to be opened till bug is not fixed (is it a bug?))

**Comment by teotwaki** [comment] 2017-04-18 14:46
Hi again @Igralino,

This seems to be more of an issue with the Ubuntu version shipped by your VPS. I'll create an issue on our internal bugtracker to add a note on the website that clarifies this. There isn't much we can do, on our end. Would you mind sharing which VPS provider you encountered this error with?

**Comment by Igralino** [comment] 2017-04-18 14:49
@teotwaki 
The Russian one. https://firstvds.ru

**Comment by teotwaki** [comment] 2017-04-18 14:58
Hi again @Igralino,

I would suggest creating a support issue with them, and asking them to enable IPv6 by default. I would expect more and more applications to break when there is no IPv6 support enabled. IPv6 connectivity doesn't need to work (though it would be beneficial for their users), but at least link-local IPv6 addressing should be available.

I'll close this for now.

**Closed by teotwaki** 2017-04-18 14:58 UTC
