### ISSUE TITLE
Latest version of Realm Browser on iOS does not scroll tables

### ISSUE THREAD

**Issue by stevewehba** [realm/realm-mobile-platform#71] opened 2016-12-15 21:28 UTC

**Comment by bigfish24** [comment] 2016-12-16 07:28
@stevewehba we don't offer a Realm Browser for iOS, is this a third-party library?

**Comment by teotwaki** [comment] 2016-12-16 13:49
@stevewehba Did you mean the macOS browser? If so, could you please provide a reproduction case? Thanks.

**Comment by teotwaki** [comment] 2016-12-27 13:12
I'm going to close this, as I'm unsure what the issue is, nor which product OP is talking about.

**Closed by teotwaki** 2016-12-27 13:12 UTC
Labels: S:Waiting For User
